#' eval.nonmem.parameter
#'
#' evaluate expression including NONMEM parameters\cr
#' assuming \code{md} is a RNMImport model returned by \code{importNmMod} \cr
#' \code{eval.nonmem.parameter} can evaluate an expression w.r.t the model's parameter's definition\cr
#' e.g.\cr
#'     \code{eval.nonmem.parameter( quote( Var(ETA[1]) ) , md)          -> Omega[1,1] } \cr
#'     \code{eval.nonmem.parameter( quote( Cov(ETA[1], ETA[2]) ) , md)  -> Omega[1,2] } \cr
#' @param e0 expression
#' @param md NONMEM model generated by \code{importNmMod}
#' @return evaluated expression
#' @author Mango solutions
eval.nonmem.parameter = function(e0, md) {
    if (is.null(md)) return(e0)
    nonmem.parameter.eval.rules = list(
        list(quote( THETA['?a'(II)] ),
            function(e,dict){
                II = dict$II
                md$Theta[ II, 'Est']
            }),
        list(quote( UpperBound(THETA['?a'(II)] )),
            function(e,dict){
                II = dict$II
                md$Theta[ II, 'Upper']
            }),
        list(quote( LowerBound(THETA['?a'(II)] )),
            function(e,dict){
                II = dict$II
                md$Theta[ II, 'Lower']
            }),
        list(quote( Var(ETA['?a'(II)] )),
            function(e,dict){
                II = dict$II
                md$Omega[ II, II]
            }),
        list(quote( Cov(ETA['?a'(II)], ETA['?a'(JJ)] )),
            function(e,dict){
                II = dict$II
                JJ = dict$JJ
                md$Omega[ II, JJ]
            }),
        list(quote( Var(EPS['?a'(II)] )),
            function(e,dict){
                II = dict$II
                md$Sigma[ II, II]
            }),
        list(quote( Cov(EPS['?a'(II)], EPS['?a'(JJ)] )),
            function(e,dict){
                II = dict$II
                JJ = dict$JJ
                md$Sigma[ II, JJ]
            }))
    walker = symbolic.simplify.gigo(nonmem.parameter.eval.rules)
    simplify.2(walker(e0))
}

